### ISSUE TITLE
pip install Flask-AP

### ISSUE THREAD

**Issue by soydepr** [flask-api/flask-api#116]
getting this error : RPI4
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting Flask-API
Could not install packages due to an EnvironmentError: 404 Client Error: Not Found for url: https://www.piwheels.org/simple/flask-api/

**Comment by soydepr** [comment]
solved updating pip

**Comment by soydepr** [comment]
i@lucas:~ $ cat flaskapi.py 
from flask import Flask, json

companies = [{"id": 1, "name": "Company One"}, {"id": 2, "name": "Company Two"}]

api = Flask(__name__)

@api.route('/companies', methods=['GET'])
def get_companies():
  return json.dumps(companies)

if __name__ == '__main__':
    api.run(host='0.0.0.0')


now i get this error ?
pi@lucas:~ $ python3 flaskapi.py 
Traceback (most recent call last):
  File "flaskapi.py", line 1, in <module>
    from flask import Flask, json
  File "/home/pi/flask.py", line 1, in <module>
    from flask_api import FlaskAPI
  File "/home/pi/.local/lib/python3.7/site-packages/flask_api/__init__.py", line 1, in <module>
    from flask_api.app import FlaskAPI
  File "/home/pi/.local/lib/python3.7/site-packages/flask_api/app.py", line 3, in <module>
    from flask import request, Flask, Blueprint
ImportError: cannot import name 'request' from 'flask' (/home/pi/flask.py
