### ISSUE TITLE
zip_safe flag not set; analyzing archive contents...ValueError: bad marshal data (unknown type code)

### ISSUE THREAD

**Issue by james-fanduel** [flask-api/flask-api#56]
When installing Flask-API as a requirement for another application via `python setup.py install` I get:

```
zip_safe flag not set; analyzing archive contents...
flask_api.tests.__init__: module references __file__
Traceback (most recent call last):
```

....

```
ValueError: bad marshal data (unknown type code)
```

**Comment by jacebrowning** [comment]
Is this only with certain versions?

**Comment by james-fanduel** [comment]
I can't seem to get it working with 0.6.4->0.6.6

**Comment by james-fanduel** [comment]
That was on Fedora 22.
Trying it on an Ubuntu VM gives me:
```
zip_safe flag not set; analyzing archive contents...
flask_api.tests.__init__: module references __file__
Traceback (most recent call last):
```
..snip...
```
  File "/usr/lib/python2.7/distutils/core.py", line 152, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/home/vagrant/.virtualenvs/redshiftfrontend/local/lib/python2.7/site-packages/setuptools/command/bdist_egg.py", line 209, in run
    os.path.join(archive_root, 'EGG-INFO'), self.zip_safe()
  File "/home/vagrant/.virtualenvs/redshiftfrontend/local/lib/python2.7/site-packages/setuptools/command/bdist_egg.py", line 245, in zip_safe
    return analyze_egg(self.bdist_dir, self.stubs)
  File "/home/vagrant/.virtualenvs/redshiftfrontend/local/lib/python2.7/site-packages/setuptools/command/bdist_egg.py", line 355, in analyze_egg
    safe = scan_module(egg_dir, base, name, stubs) and safe
  File "/home/vagrant/.virtualenvs/redshiftfrontend/local/lib/python2.7/site-packages/setuptools/command/bdist_egg.py", line 395, in scan_module
    symbols = dict.fromkeys(iter_symbols(code))
  File "/home/vagrant/.virtualenvs/redshiftfrontend/local/lib/python2.7/site-packages/setuptools/command/bdist_egg.py", line 414, in iter_symbols
    for name in code.co_names:
AttributeError: 'bool' object has no attribute 'co_names'
```

**Comment by jacebrowning** [comment]
I'm not really sure what's going on. Is there a newer version of `setuptools` to install?

**Comment by james-fanduel** [comment]
```
> which easy_install                     
> ~/my_app/env/bin/easy_install

> ~/my_app/env/bin/easy_install --version
> setuptools 22.0.0 from /home/james/my_app/env/lib/python2.7/site-packages (Python 2.7)
```

**Comment by jacebrowning** [comment]
This doesn't appear to be an issue with Flask API itself. Please reopen if you think otherwise.
